name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: "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"
